
export const allPatchProducts = [
  {
    id: 1,
    name: "Custom Patch",
    category: "Custom",
    rating: 5,
    priceMin: 299,
    priceMax: 499,
    priceLabel: "₱ 299 - 499",
    image: "", // leave blank for now
  },
  {
    id: 2,
    name: "Military Patch",
    category: "Military",
    rating: 4,
    priceMin: 349,
    priceMax: 549,
    priceLabel: "₱ 349 - 549",
    image: "",
  },
  {
    id: 3,
    name: "Name Patch",
    category: "Name",
    rating: 4,
    priceMin: 249,
    priceMax: 399,
    priceLabel: "₱ 249 - 399",
    image: "",
  },
  {
    id: 4,
    name: "Flag Patch",
    category: "Flag",
    rating: 3,
    priceMin: 199,
    priceMax: 299,
    priceLabel: "₱ 199 - 299",
    image: "",
  },
  {
    id: 5,
    name: "Logo Patch",
    category: "Logo",
    rating: 5,
    priceMin: 399,
    priceMax: 599,
    priceLabel: "₱ 399 - 599",
    image: "",
  },
  {
    id: 6,
    name: "Tactical Patch",
    category: "Tactical",
    rating: 4,
    priceMin: 299,
    priceMax: 499,
    priceLabel: "₱ 299 - 499",
    image: "",
  },
  {
    id: 7,
    name: "Embroidered Text",
    category: "Text",
    rating: 3,
    priceMin: 199,
    priceMax: 299,
    priceLabel: "₱ 199 - 299",
    image: "",
  },
  {
    id: 8,
    name: "Symbol Patch",
    category: "Symbol",
    rating: 4,
    priceMin: 249,
    priceMax: 449,
    priceLabel: "₱ 249 - 449",
    image: "",
  },
  {
    id: 9,
    name: "Unit Patch",
    category: "Military",
    rating: 5,
    priceMin: 399,
    priceMax: 599,
    priceLabel: "₱ 399 - 599",
    image: "",
  },
  {
    id: 10,
    name: "Custom Symbol",
    category: "Custom",
    rating: 4,
    priceMin: 349,
    priceMax: 549,
    priceLabel: "₱ 349 - 549",
    image: "",
  },
];
